### ISSUE TITLE
In DRF, Middleware which uses request.user is always Anonymous

### ISSUE THREAD

**Issue by zhiming429438709** [pycasbin/django-casbin#10]
In DRF, Middleware which uses request.user is always Anonymous, but in view, the user is not anonymous

**Comment by Nekotoxin** [comment]
hello, what is "DRF"?

**Comment by hsluoyz** [comment]
@Nekotoxin @zhiming429438709 I think it's https://www.django-rest-framework.org/ ?

**Comment by hsluoyz** [comment]
Closed as resolved
