### ISSUE TITLE
Can this extension be posted to Anaconda?

### ISSUE THREAD

**Issue by silentmissile** [pycasbin/django-casbin#3]
The Python distribution I use is Anaconda. Can this extension be posted as a conda package to Anaconda? I am afraid that the pip package is not compatible with Anaconda.

**Comment by techoner** [comment]
Try it with `pip`.

**Comment by hsluoyz** [comment]
@silentmissile is this issue still valid?

**Comment by hsluoyz** [comment]
Closed as stale.
