### ISSUE TITLE
Can you add some actual demos as sample code?

### ISSUE THREAD

**Issue by allran** [pycasbin/django-casbin#4]
RT

**Comment by techoner** [comment]
You can refer to the [official website](https://casbin.org/docs/en/overview), many examples are in it.

**Comment by allran** [comment]
I read the docs, and no find the UI to set it like Django Admin setting. I only find the go language demo. can you tell me how can I use UI to set user permission, thanks!

**Comment by techoner** [comment]
The Web UI for Casbin：https://github.com/casbin/web-ui
