### ISSUE TITLE
Is this project still ongoing?

### ISSUE THREAD

**Issue by okapies** [pycasbin/django-casbin#5]
I'm interested in using casbin in our Django project, but it seems it is not actively maintained. Is `django-casbin` is still available for the latest version of Django?

**Comment by hsluoyz** [comment]
@okapies yes, we are still maintaining it.

@ffyuanda @Zxilly can you update the version?

/cc @techoner

**Comment by Zxilly** [comment]
@hsluoyz You mean update the dependency?

**Comment by okapies** [comment]
Thanks!

**Comment by hsluoyz** [comment]
@Zxilly yes

**Comment by hsluoyz** [comment]
@fabian4
