### ISSUE TITLE
Can we make an example project based on this repo (django-casbin) ?

### ISSUE THREAD

**Issue by hsluoyz** [pycasbin/django-casbin#6]
See Gitter:

![image](https://user-images.githubusercontent.com/3787410/132985730-3a75aa0f-84e1-4691-8dd6-9b3f462d0c81.png)

**Comment by hsluoyz** [comment]
@ffyuanda @Zxilly

/c @techoner

**Comment by ffyuanda** [comment]
will try to set an example sooner

**Comment by hsluoyz** [comment]
Partially replaced by: https://github.com/pycasbin/django-authorization/issues/8
